### ISSUE TITLE
[Question] would you accept contribution to Cozmopedia ?

### ISSUE THREAD

**Issue by ireallydontexist** [touretzkyds/cozmopedia#1]
I think this Cozmopedia  is an excellent idea ! If I fork it, add content then propose a pull request, would you integrate it (if relevant of course) ?

**Comment by touretzkyds** [comment]
Ultimately I would love to receive contributions to Cozmopedia. But it's in its very early stages right now and is likely to change significantly in the coming month. It hasn't even been publicly announced yet. Heck, I don't even have the logo installed yet. So rather than forking it right now, I would prefer that we discussed what changes you have in mind. I'm very interested to hear your ideas!

**Comment by ireallydontexist** [comment]
Ok. Sent by email to your profile's email address.
